# Challenge: using parameters from json_normalize

When normalizing a JSON object during the lesson, we simply used `pd.json_normalize(<data>)`; however, the `json_normalize` method includes several parameters for handling more complex data structures.

***

You have been tasked with normalizing the following JSON file, named “[informacoes.json](https://cdn3.gnarususercontent.com.br/2929-pandas/informacoes.json)” which contains identification information for a client. The file has the following content:

In [1]:
import pandas as pd
import json

In [4]:
data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/exercises/resources/informacoes.json')
data

   nome  idade                                          enderecos
0  João     28  {'tipo': 'casa', 'rua': 'Rua A', 'numero': 123...
1  João     28  {'tipo': 'trabalho', 'rua': 'Rua B', 'numero':...

In [7]:
with open('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/exercises/resources/informacoes.json', 'r') as f:
  raw_json = json.load(f)

In [9]:
raw_json

{'nome': 'João',
 'idade': 28,
 'enderecos': [{'tipo': 'casa',
   'rua': 'Rua A',
   'numero': 123,
   'cidade': 'São Paulo'},
  {'tipo': 'trabalho',
   'rua': 'Rua B',
   'numero': 456,
   'cidade': 'Rio de Janeiro'}]}

In [13]:
normalized_data = pd.json_normalize(raw_json, record_path='enderecos', meta=['nome', 'idade'])

In [14]:
normalized_data

       tipo    rua  numero          cidade  nome idade
0      casa  Rua A     123       São Paulo  João    28
1  trabalho  Rua B     456  Rio de Janeiro  João    28