# Challenge: time to practice

It’s time to practice! Let’s apply the concepts learned during the lesson through a few activities. Solve the proposed problems by writing code, using the dataset provided in the course.

1. Group the data based on the "Level 1 - Setor" column to view the dictionary containing the keys for the formed groups and the list of indices for each group.

2. Group the data based on the "Nível 1 - Setor" column and locate the data for the "Agriculture and Livestock" (Agropecuária) group.

3. Group the data based on the ""Nível 1 - Setor" column to determine the average emissions for each sector in the year 2021.

4. Group the data based on the ""Nível 1 - Setor" column to determine the total emissions for each sector. Sort the data from the highest to the lowest emission levels.

In [12]:
import pandas as pd

In [16]:
gas_emissions = pd.read_csv('/content/emissions_per_year.csv')
gas_emissions.head(4)

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Gás,Estado,Atividade Econômica,Produto,Year,Emission
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,COVNM (t),SP,OUTRA_IND,NaN,1970.0,0.0
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,N2O (t),SP,OUTRA_IND,NaN,1970.0,6210.0
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,CO (t),SP,OUTRA_IND,NaN,1970.0,368.0
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,NOx (t),SP,OUTRA_IND,NaN,1970.0,115.0

1. Group the data based on the "Level 1 - Sector" column to view the dictionary containing the keys for the formed groups and the list of indices for each group.

In [17]:
gas_emissions.groupby('Nível 1 - Setor').groups

{'Agropecuária': [1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, ...], 'Energia': [24735, 24736, 24737, 24738, 24739, 24740, 24741, 24742, 24743, 24744, 24745, 24746, 24747, 24748, 24749, 24750, 24751, 24752, 24753, 24754, 24755, 24756, 24757, 24758, 24759, 24760, 24761, 24762, 24763, 24764, 24765, 24766, 24767, 24768, 24769, 24770, 24771, 24772, 24773, 24774, 24775, 24776, 24777, 24778, 24779, 24780, 24781, 24782, 24783, 24784, 24785, 24786, 24787, 24788, 24789, 24790, 24791, 24792, 24793, 24794, 24795, 24796, 24797, 24798, 24799, 24800, 24801, 24802, 24803, 24804, 24805, 24806, 24807, 24808, 24809, 24810, 24811, 24812, 24813, 24814, 24815, 24816, 24817, 24818, 24819, 24820, 24821, 24822, 24823, 24824, 24825, 24826, 24827, 24828, 24829, 24830, 24831, 24832, 24833, 24834, ...], 'Mudança de Uso da Terra e Floresta': [81260, 81261, 81262, 81263, 81264, 81265, 81266, 81267, 81268, 81269, 81270, 81271, 81272, 81273, 81274, 81275, 81276, 81277, 81278, 81279, 81280, 81281, 81282, 81283, 81284, 81285, 81286, 81287, 81288, 81289, 81290, 81291, 81292, 81293, 81294, 81295, 81296, 81297, 81298, 81299, 81300, 81301, 81302, 81303, 81304, 81305, 81306, 81307, 81308, 81309, 81310, 81311, 81312, 81313, 81314, 81315, 81316, 81317, 81318, 81319, 81320, 81321, 81322, 81323, 81324, 81325, 81326, 81327, 81328, 81329, 81330, 81331, 81332, 81333, 81334, 81335, 81336, 81337, 81338, 81339, 81340, 81341, 81342, 81343, 81344, 81345, 81346, 81347, 81348, 81349, 81350, 81351, 81352, 81353, 81354, 81355, 81356, 81357, 81358, 81359, ...], 'Processos Industriais': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...], 'Resíduos ': [77444, 77445, 77446, 77447, 77448, 77449, 77450, 77451, 77452, 77453, 77454, 77455, 77456, 77457, 77458, 77459, 77460, 77461, 77462, 77463, 77464, 77465, 77466, 77467, 77468, 77469, 77470, 77471, 77472, 77473, 77474, 77475, 77476, 77477, 77478, 77479, 77480, 77481, 77482, 77483, 77484, 77485, 77486, 77487, 77488, 77489, 77490, 77491, 77492, 77493, 77494, 77495, 77496, 77497, 77498, 77499, 77500, 77501, 77502, 77503, 77504, 77505, 77506, 77507, 77508, 77509, 77510, 77511, 77512, 77513, 77514, 77515, 77516, 77517, 77518, 77519, 77520, 77521, 77522, 77523, 77524, 77525, 77526, 77527, 77528, 77529, 77530, 77531, 77532, 77533, 77534, 77535, 77536, 77537, 77538, 77539, 77540, 77541, 77542, 77543, ...]}

2. Group the data based on the "Nível 1 - Setor" column and locate the data for the "Agriculture and Livestock" (Agropecuária) group.

In [18]:
gas_emissions.groupby('Nível 1 - Setor').get_group('Agropecuária')

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Gás,Estado,Atividade Econômica,Produto,Year,Emission
1137,Agropecuária,Cultivo de Arroz,Diretas,Outros,Vegetal,Arroz,CH4 (t),AC,AGR,ALIM_BEBIDAS,1970.0,0.000000
1138,Agropecuária,Cultivo de Arroz,Diretas,Outros,Vegetal,Arroz,CH4 (t),AL,AGR,ALIM_BEBIDAS,1970.0,2050.445805
1139,Agropecuária,Cultivo de Arroz,Diretas,Outros,Vegetal,Arroz,CH4 (t),AM,AGR,ALIM_BEBIDAS,1970.0,0.000000
1140,Agropecuária,Cultivo de Arroz,Diretas,Outros,Vegetal,Arroz,CH4 (t),AP,AGR,ALIM_BEBIDAS,1970.0,0.000000
1141,Agropecuária,Cultivo de Arroz,Diretas,Outros,Vegetal,Arroz,CH4 (t),BA,AGR,ALIM_BEBIDAS,1970.0,466.934705
...,...,...,...,...,...,...,...,...,...,...,...,...
831688,Agropecuária,Manejo de Dejetos Animais,Diretas,Outros,Animal,Gado de Leite,CO2e (t) GTP-AR6,CE,PEC,LEI,1978.0,7666.015653
831689,Agropecuária,Manejo de Dejetos Animais,Diretas,Outros,Animal,Gado de Leite,CO2e (t) GTP-AR6,DF,PEC,LEI,1978.0,498.715571
831690,Agropecuária,Manejo de Dejetos Animais,Diretas,Outros,Animal,Gado de Leite,CO2e (t) GTP-AR6,ES,PEC,LEI,1978.0,9375.379922
831691,Agropecuária,Manejo de Dejetos Animais,Diretas,Outros,Animal,Gado de Leite,CO2e (t) GTP-AR6,GO,PEC,LEI,1978.0,42107.907699
831692,Agropecuária,Manejo de Dejetos Animais,Diretas,Outros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. Group the data based on the ""Nível 1 - Setor" column to determine the average emissions for each sector in the year 2021.

In [23]:
gas_emissions[gas_emissions['Year'] == 2021].groupby('Nível 1 - Setor')[['Emission']].mean()

Empty DataFrame
Columns: [Emission]
Index: []

4. Group the data based on the ""Nível 1 - Setor" column to determine the total emissions for each sector. Sort the data from the highest to the lowest emission levels.

In [24]:
gas_emissions.groupby('Nível 1 - Setor')[['Emission']].sum().sort_values('Emission', ascending = False)

                                        Emission
Nível 1 - Setor
Agropecuária                        1.120810e+10
Energia                             9.440125e+09
Processos Industriais               1.683809e+09
Resíduos                            4.623716e+08
Mudança de Uso da Terra e Floresta  0.000000e+00