# Challenge: time to practice

It’s time to practice! Let’s apply the concepts learned during the lesson through a few activities. Solve the proposed problems by writing code, using the dataset provided in the course.

1) Group the data by the columns "Estado" and "Nível 1 - Setor," calculate the sum of emissions, and store the result in a table.

2) Using the table created in activity 1, select the data corresponding to "Energia" under the "Nível 1 - Setor" category.

3) Using the table created in activity 1, identify the economic activity with the highest emission value for the state of Minas Gerais.

4) Create a table containing the economic activity with the highest emissions for each state.

5) Create a table containing the state with the highest emissions for each economic activity.

In [1]:
import pandas as pd

In [15]:
gas_per_year = pd.read_csv('/content/gas_per_year.csv')
gas_per_year.head()

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,Produto,Year,Emission
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,NaN,1970,0.0
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,NaN,1970,6210.0
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,NaN,1970,368.0
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,NaN,1970,115.0
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,NaN,1970,1925100.0

1. Group the data by the columns "Estado" and "Nível 1 - Setor," calculate the sum of emissions, and store the result in a table.

In [38]:
state_emission_sector = gas_per_year.groupby(['Estado', 'Nível 1 - Setor'])[['Emission']].sum()
state_emission_sector

                                               Emission
Estado Nível 1 - Setor
AC     Agropecuária                       -3.272006e+08
       Energia                             2.071751e+08
       Mudança de Uso da Terra e Floresta  4.704492e+09
       Resíduos                            2.928323e+07
AL     Agropecuária                        1.215829e+09
...                                                 ...
TO     Agropecuária                        2.789108e+09
       Energia                             5.130379e+08
       Mudança de Uso da Terra e Floresta  6.486598e+09
       Processos Industriais               2.613905e+07
       Resíduos                            6.177003e+07

[133 rows x 1 columns]

2) Using the table created in activity 1, select the data corresponding to "Energia" under the "Nível 1 - Setor" category.

In [39]:
state_emission_sector.xs('Energia', level=1)

            Emission
Estado
AC      2.071751e+08
AL      5.958697e+08
AM      1.916462e+09
AP      2.638059e+08
BA      4.801368e+09
CE      1.879584e+09
DF      9.487860e+08
ES      2.201326e+09
GO      2.761709e+09
MA      1.699005e+09
MG      9.663844e+09
MS      1.593967e+09
MT      2.296983e+09
PA      2.730706e+09
PB      8.358578e+08
PE      2.089593e+09
PI      5.044902e+08
PR      5.502734e+09
RJ      9.151787e+09
RN      9.473144e+08
RO      7.246552e+08
RR      1.672719e+08
RS      5.901596e+09
SC      4.328366e+09
SE      6.627356e+08
SP      2.214979e+10
TO      5.130379e+08

3) Using the table created in activity 1, identify the economic activity with the highest emission value for the state of Minas Gerais.

In [41]:
state_emission_sector.xs('MG', level=0)[['Emission']].idxmax()

Emission    Agropecuária
dtype: object

4) Create a table containing the economic activity with the highest emissions for each state.

In [44]:
highest_activity_per_state = state_emission_sector.groupby(level=0).idxmax()
highest_activity_per_state

                                        Emission
Estado
AC      (AC, Mudança de Uso da Terra e Floresta)
AL                            (AL, Agropecuária)
AM                                 (AM, Energia)
AP                                 (AP, Energia)
BA                            (BA, Agropecuária)
BR      (BR, Mudança de Uso da Terra e Floresta)
CE                            (CE, Agropecuária)
DF                                 (DF, Energia)
ES                   (ES, Processos Industriais)
GO                            (GO, Agropecuária)
MA      (MA, Mudança de Uso da Terra e Floresta)
MG                            (MG, Agropecuária)
MS                            (MS, Agropecuária)
MT      (MT, Mudança de Uso da Terra e Floresta)
PA      (PA, Mudança de Uso da Terra e Floresta)
PB                            (PB, Agropecuária)
PE                            (PE, Agropecuária)
PI                            (PI, Agropecuária)
PR                            (PR, Agropecuária)
RJ                                 (RJ, Energia)
RN                                 (RN, Energia)
RO      (RO, Mudança de Uso da Terra e Floresta)
RR                                 (RR, Energia)
RS                            (RS, Agropecuária)
SC                                 (SC, Energia)
SE                            (SE, Agropecuária)
SP                                 (SP, Energia)
TO      (TO, Mudança de Uso da Terra e Floresta)

5) Create a table containing the state with the highest emissions for each economic activity.

In [45]:
highest_emission_per_state = state_emission_sector.groupby(level=1).idxmax()
highest_emission_per_state

                                                                    Emission
Nível 1 - Setor
Agropecuária                                              (MG, Agropecuária)
Energia                                                        (SP, Energia)
Mudança de Uso da Terra e Floresta  (MT, Mudança de Uso da Terra e Floresta)
Processos Industriais                            (MG, Processos Industriais)
Resíduos                                                     (SP, Resíduos )