# Understanding the data

In [58]:
import pandas as pd
import numpy as np

In [59]:
normalized_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/resources/telecon_normalized_data_v1.json')
normalized_data.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,None
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

# Initial data transformation

### Telcon data dictionary

Customer

- `gender`: gender (male or female)
- `senior`: indicates whether the customer is 65 years of age or older
- `partner`: whether the customer has a partner
- `dependents`: whether the customer has dependents
- `tenure`: number of months the customer has been under contract

Telephone Service

- `phone_service`: subscription to telephone service
- `multiple_lines`: subscription to more than one telephone line

Internet Service

- `internet_service`: subscription to an internet service provider
- `online_security`: additional subscription for online security
- `online_backup`: additional subscription for online backup
- `device_protection`: additional subscription for device protection
- `technical_support`: additional subscription for technical support (with shorter wait times)
- `cable_tv`: subscription to cable TV
- `movie_streaming`: subscription to a movie streaming service

Account

- `contract`: type of contract
- `paperless_billing`: whether the customer prefers to receive bills online
- `payment_method`: method of payment
- `monthly_charges`: total cost of all the customer's services per month
- `total_charges`: total amount spent by the customer

In [60]:
normalized_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.2+ MB

### Identifying outliers values

In [61]:
normalized_data['conta.cobranca.Total'] = normalized_data['conta.cobranca.Total'].astype(float)

ValueError: could not convert string to float: ' '

We received the message:
- `ValueError: could not convert string to float`

This means there is an unusual string in this column, which is why it has been assigned the `object` data type.

Above, by using `info()` on our dataframe, we saw that this column contains some null values, which could be the cause of our problem.

We need to handle this anomalous value in the column before performing the cast. We will do it next.

### Modifying the column type

In [62]:
normalized_data[normalized_data['conta.cobranca.Total'] == ' '].head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
975,1371-DWPAZ,nao,feminino,0,sim,sim,0.0,nao,sem servico de telefone,DSL,...,sim,sim,sim,sim,nao,dois anos,nao,cartao de credito (automatico),56.05,
1775,2520-SGTTA,nao,feminino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.00,
1955,2775-SEFEE,nao,masculino,0,nao,sim,0.0,sim,sim,DSL,...,sim,nao,sim,nao,nao,dois anos,sim,transferencia bancaria (automatica),61.90,
2075,2923-ARZLG,nao,masculino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cheque pelo correio,19.70,
2232,3115-CZMZD,nao,masculino,0,nao,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.25,

We can see that the `conta.cobranca.Total` column is empty in the returned rows, which makes it impossible to convert the column's data type.

Furthermore, there is some suspicious data. While the `conta.cobranca.mensal` column contains different values ​​for each row, the `conta.contrato` column shows the same value (two years) across all rows; meanwhile, the `cliente.tempo_servico` column shows a value of zero for every single row.

***
We will carefully examine the four aforementioned columns to determine whether any relationship exists between them.

In [63]:
normalized_data[normalized_data['conta.cobranca.Total'] == ' '][
    ['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total']
]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,0.0,dois anos,56.05,
1775,0.0,dois anos,20.00,
1955,0.0,dois anos,61.90,
2075,0.0,dois anos,19.70,
2232,0.0,dois anos,20.25,
2308,0.0,dois anos,25.35,
2930,0.0,dois anos,73.35,
3134,0.0,dois anos,25.75,
3203,0.0,dois anos,52.55,
4169,0.0,dois anos,80.85,
5599,0.0,dois anos,19.85,

After analyzing the columns containing missing or odd data, we can infer that, since the contract duration is two years in all cases, the customer's tenure at the end of this period will be 24 months. Based on this finding, we can simply multiply `cliente.tempo_servico` (24 months) by `conta.cobranca.mensal` to determine the value for `conta.cobranca.Total`.

In [64]:
idx = normalized_data[normalized_data['conta.cobranca.Total'] == ' '].index
idx

Index([975, 1775, 1955, 2075, 2232, 2308, 2930, 3134, 3203, 4169, 5599], dtype='int64')

In [65]:

normalized_data.loc[idx, "conta.cobranca.Total"] = normalized_data.loc[idx, "conta.cobranca.mensal"] * 24

In [66]:
normalized_data.loc[idx, "cliente.tempo_servico"] = 24

In [67]:
normalized_data.loc[idx][
    ['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total']
]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,24.0,dois anos,56.05,1345.2
1775,24.0,dois anos,20.00,480.0
1955,24.0,dois anos,61.90,1485.6
2075,24.0,dois anos,19.70,472.8
2232,24.0,dois anos,20.25,486.0
2308,24.0,dois anos,25.35,608.4
2930,24.0,dois anos,73.35,1760.4
3134,24.0,dois anos,25.75,618.0
3203,24.0,dois anos,52.55,1261.2
4169,24.0,dois anos,80.85,1940.4
5599,24.0,dois anos,19.85,476.4

After processing our columns, we will attempt to modify the data type again by performing the cast.

In [68]:
normalized_data['conta.cobranca.Total'] = normalized_data['conta.cobranca.Total'].astype(float)

In [69]:
normalized_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   float64
dtypes: float64(3), int64(1), object(17)
memory usage: 1.5+ MB

# Identifying and Handling Empty Strings

In [70]:
for col in normalized_data.columns:
  print(f'Column: {col}')
  print(normalized_data[col].unique())
  print('-' * 40)

Column: id_cliente
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
----------------------------------------
Column: Churn
['nao' 'sim' '']
----------------------------------------
Column: cliente.genero
['feminino' 'masculino']
----------------------------------------
Column: cliente.idoso
[0 1]
----------------------------------------
Column: cliente.parceiro
['sim' 'nao']
----------------------------------------
Column: cliente.dependentes
['sim' 'nao']
----------------------------------------
Column: cliente.tempo_servico
[9.00e+00 4.00e+00 1.30e+01 3.00e+00 7.10e+01 6.30e+01 7.00e+00      nan
 5.40e+01 7.20e+01 5.00e+00 5.60e+01 3.40e+01 1.00e+00 4.50e+01 5.00e+01
 2.30e+01 5.50e+01 2.60e+01 6.90e+01 1.10e+01 3.70e+01 4.90e+01 6.60e+01
 6.70e+01 2.00e+01 4.30e+01 5.90e+01 1.20e+01 2.70e+01 2.00e+00 2.50e+01
 2.90e+01 1.40e+01 3.50e+01 6.40e+01 3.90e+01 4.00e+01 6.00e+00 3.00e+01
 7.00e+01 5.70e+01 5.80e+01 1.60e+01 3.20e+01 3.30e+01 1.00e+01 2.10e+01
 6.10e+01 1.50e+01 4.40e+01 2.20e+01 2.40e+01 1.90e+01 4.70e+01 6.20e+01
 4.60e+01 5.20e+01 8.00e+00 6.00e+01 4.80e+01 2.80e+01 6.50e+01 4.10e+01
 5.30e+01 6.80e+01 5.10e+01 3.10e+01 3.60e+01 1.70e+01 1.80e+01 3.80e+01
 4.20e+01 1.08e+03 1.00e+03 9.50e+02 2.54e+02 3.21e+02 6.50e+02 7.00e+02
 7.21e+02 5.55e+02 4.33e+02 5.12e+02]
----------------------------------------
Column: telefone.servico_telefone
['sim' 'nao']
----------------------------------------
Column: telefone.varias_linhas
['nao' 'sim' 'sem servico de telefone']
----------------------------------------
Column: internet.servico_internet
['DSL' 'fibra otica' 'nao']
----------------------------------------
Column: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.backup_online
['sim' 'nao' 'sem servico de internet']
----------------------------------------
Column: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.suporte_tecnico
['sim' 'nao' 'sem servico de internet']
----------------------------------------
Column: internet.tv_streaming
['sim' 'nao' 'sem servico de internet']
----------------------------------------
Column: internet.filmes_streaming
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: conta.contrato
[None 'mes a mes' 'dois anos' 'um ano']
----------------------------------------
Column: conta.faturamente_eletronico
[None 'nao' 'sim']
----------------------------------------
Column: conta.metodo_pagamento
[None 'cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
----------------------------------------
Column: conta.cobranca.mensal
[  nan 59.9  73.9  ... 91.75 68.8  67.85]
----------------------------------------
Column: conta.cobranca.Total
[    nan  542.4   280.85 ...  742.9  4627.65 3707.6 ]
----------------------------------------

In [71]:
normalized_data.query('Churn == ""')

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
30,0047-ZHDTW,,feminino,0,nao,nao,11.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,transferencia bancaria (automatica),79.00,929.30
75,0120-YZLQA,,masculino,0,nao,nao,71.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cartao de credito (automatico),19.90,1355.10
96,0154-QYHJU,,masculino,0,nao,nao,29.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,um ano,sim,cheque eletronico,58.75,1696.20
98,0162-RZGMZ,,feminino,1,nao,nao,5.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,mes a mes,nao,cartao de credito (automatico),59.90,287.85
175,0274-VVQOQ,,masculino,1,sim,nao,65.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,um ano,sim,transferencia bancaria (automatica),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7211,9920-GNDMB,,masculino,0,nao,nao,9.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,cheque eletronico,76.25,684.85
7239,9955-RVWSC,,feminino,0,sim,sim,67.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,transferencia bancaria (automatica),19.25,1372.90
7247,9966-VYRTZ,,feminino,0,sim,sim,31.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,mes a mes,sim,cheque pelo correio,19.55,658.95
7267,6532-YOHZY,,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,transferencia bancaria (automatica),109.75,4900.65
7342,3601-UTZXO,,masculino,0,sim,sim,41.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,transferencia bancaria (automatica),19.50,798.20

The 'Churn' column is the target for our machine learning model, therefore, it makes no sense to have samples that lack data in this column. For this reason, we will discard these entries.

## Discarding samples

Since we want to work independently with the new dataframe `no_empty_data`, we need to create an independent copy. This way, if we modify the new dataframe, the original one `normalized_data` will not be affected.

### Creating a copy of the dataframe

In [74]:
no_empty_data = normalized_data[normalized_data['Churn'] != ''].copy()

In [75]:
no_empty_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7118 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7118 non-null   object
 1   Churn                          7118 non-null   object
 2   cliente.genero                 7118 non-null   object
 3   cliente.idoso                  7118 non-null   int64
 4   cliente.parceiro               7118 non-null   object
 5   cliente.dependentes            7118 non-null   object
 6   cliente.tempo_servico          7110 non-null   float64
 7   telefone.servico_telefone      7118 non-null   object
 8   telefone.varias_linhas         7118 non-null   object
 9   internet.servico_internet      7118 non-null   object
 10  internet.seguranca_online      7118 non-null   object
 11  internet.backup_online         7118 non-null   object
 12  internet.protecao_dispositivo  7118 non-null   object
 13  internet.suporte_tecnico       7118 non-null   object
 14  internet.tv_streaming          7118 non-null   object
 15  internet.filmes_streaming      7118 non-null   object
 16  conta.contrato                 7086 non-null   object
 17  conta.faturamente_eletronico   7100 non-null   object
 18  conta.metodo_pagamento         7091 non-null   object
 19  conta.cobranca.mensal          7100 non-null   float64
 20  conta.cobranca.Total           7102 non-null   float64
dtypes: float64(3), int64(1), object(17)
memory usage: 1.2+ MB

***
Correcting the sample index

In [77]:
no_empty_data.reset_index(drop=True, inplace=True)

In [78]:
no_empty_data

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7114,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7115,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7116,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7117,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

In [79]:
normalized_data.to_json('telecon_normalized_data_v2')

In [80]:
no_empty_data.to_json('churn_subset_without_empty_data_v1.json')